name: Build and deploy GH Pages

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build and deploy
        uses: shalzz/zola-deploy-action@v0.20.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: gh-pages
          cname: blog.techarcanus.com
